### ISSUE TITLE
1.3.11 release is broken

### ISSUE THREAD

**Issue by jensens** [plone/Products.TinyMCE#110]
Problem::

    Getting distribution for 'Products.TinyMCE==1.3.11'.
    error: [Errno 2] No such file or directory: 'HISTORY.rst'
    An error occurred when trying to install Products.TinyMCE 1.3.11. Look above this message for any errors that were output by easy_install.
    While:
      Installing instance.
      Getting distribution for 'Products.TinyMCE==1.3.11'.
    Error: Couldn't install: Products.TinyMCE 1.3.11

Happens in coredev4, i.e. jenkins here: http://jenkins.plone.org/job/plone-4.3-python-2.7/605/console

**Comment by mauritsvanrees** [comment]
I had no problems locally with 1.3.11. I have released 1.3.12. Let's see if that helps.

**Comment by mauritsvanrees** [comment]
That did not help.

I have edited setup.cfg to always create zip files instead of tar.gz files. I have released 1.3.13 and that one finally works fine on Jenkins.
