### ISSUE TITLE
Linkable types in GS profile only defines "Topic" portal type.

### ISSUE THREAD

**Issue by rnixx** [plone/Products.TinyMCE#112]
https://github.com/plone/Products.TinyMCE/blob/master/Products/TinyMCE/profiles/default/tinymce.xml#L8

"Collection" should also be added in order to please installations with new "Collection" portal type.

**Comment by jensens** [comment]
hmm, I can link Collections by default in Plone 5 rc2 - how can i reproduce it in UI?

**Comment by rnixx** [comment]
> how can i reproduce it in UI
Try reference a link to a collection in TinyMCE via internal link. Linkable types are filtered by portal type

**Comment by jensens** [comment]
Well, that worked here: 

1. add a collection with some dummy query and save
2. click edit on front-page
3. mark text and click on link icon
4. select new created collection

**Comment by mauritsvanrees** [comment]
This is in Plone 4. Plone 5 does not use Products.TinyMCE.
This was fixed with pull request #143. The fix is available in Products.TinyMCE 1.3.21.
