### ISSUE TITLE
Products.TinyMCE 1.2.18

### ISSUE THREAD

**Issue by msom** [plone/Products.TinyMCE#133]
Can you make a release 1.2.18?

**Comment by msom** [comment]
@keul Do you have any idea, why your fixes never got released?

**Comment by keul** [comment]
@msom probably because TinyMCE 1.2 behold to Plone 4.2.x that is an unmantained version.

**Comment by mauritsvanrees** [comment]
I might as well release it. There you go. :-)
https://pypi.python.org/pypi/Products.TinyMCE/1.2.18

**Comment by msom** [comment]
Great, thanks a lot! :)
