### ISSUE TITLE
TinyMCE cannot insert pictures in pages

### ISSUE THREAD

**Issue by mgw** [plone/Products.TinyMCE#140]
it is not possible to insert images inside document type 'page' using TinyMCE, it seems. The pictures can not be selected, i.e. the selection disappears once you hit the button with no 
effect. The same behaviour on android smartphone firefox, or if chromium used instead of 
firefox on ubuntu 14.04 LTS. Checked reproducability of error in other demo installation of Plone 5.
This error is critical for production use of Plone 5.0.4 .

Encountered using 
    Plone 5.0.4 (5015)
    CMF 2.2.10
    Zope 2.13.24
    Python 2.7.9 (default, Mar 1 2015, 18:22:53) [GCC 4.9.2]
    PIL 3.1.1 (Pillow)

**Comment by mgw** [comment]
How do I replace the current plone.app.content with 3.0.21?

**Comment by davilima6** [comment]
@mgw, you get it from Github. You can do that by running buildout after configuring mr.developer, see:

* https://pypi.python.org/pypi/mr.developer
* https://example-plone-developement-tools.readthedocs.org/en/latest/#manage-development-eggs-with-mr-developer
* http://stackoverflow.com/questions/12448768/install-plone-add-on-from-source-instructions-for-complete-newbie/12449800#12449800

**Comment by mgw** [comment]
Ok with plone.app.content replaced by version 3.0.21, the bug is gone. Cool. Will it be included in the release soon?

**Comment by davilima6** [comment]
It will be included in Plone 5.0.5 and 5.1a2.
