### ISSUE TITLE
Vertical alignment in table row properties not working

### ISSUE THREAD

**Issue by jladage** [plone/Products.TinyMCE#144]
After selecting a cell in a table and clicking the "Row Properties" button as overlay appears with options alignment and vertical alignment. When setting the "Alignment" property to "center" a style attribute is set. And after saving the page and editing it again, selecting the row properties does seem to "remember" which alignment I choose.

When I set the "Vertical Alignment" to top/middle/bottom, nothing happens.

Tested with Plone 4.3.10-pending including Products.Tinymce 1.3.21 on Chrome 51 and Firefox 47

**Comment by mauritsvanrees** [comment]
This was fixed with pull request #145
