### ISSUE TITLE
Missing translations for Braziliam Portuguese

### ISSUE THREAD

**Issue by rodfersou** [plone/Products.TinyMCE#99]
The .po file for Braziliam Portuguese translation was located into pt (Portugal Portuguese) folder when it should be into pt_BR.

I'm coping this file into the right place with this issue and pull request.

**Comment by hvelarde** [comment]
@rodfersou this has to be fixed in the [1.3.x branch](https://github.com/plone/Products.TinyMCE/tree/1.3.x) also

**Comment by rodfersou** [comment]
@hvelarde ok, thank you

**Comment by rodfersou** [comment]
Fixed on #102
